from django.urls import path

from .views import (
    DashboardView,
    GoogleLoginView,
    HomePageView,
    LessonDetailView,
    LessonListView,
    LessonMetaView,
    LessonProgressUpdateView,
    LessonTestSubmitView,
    LessonTestView,
    LessonVocabularyView,
    RegisterView,
    StudioAuditLogView,
    StudioLessonDetailView,
    StudioLessonTemplateView,
    StudioLessonTestsView,
    StudioLessonVocabularyView,
    StudioStudentsProgressView,
    StudioTestAnalyticsView,
    StudioVocabularyView,
    StudioVocabularyDetailView,
    VocabularyQuizGenerateView,
    VocabularyQuizHistoryView,
    VocabularyQuizSubmitView,
    VocabularyListView,
    test_api,
)

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("test/", test_api, name="test_api"),
    path("register/", RegisterView.as_view(), name="register"),
    path("auth/google-login/", GoogleLoginView.as_view(), name="google_login"),
    path("home/", HomePageView.as_view(), name="home_page"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("lessons/", LessonListView.as_view(), name="lessons"),
    path("lessons/meta/", LessonMetaView.as_view(), name="lessons_meta"),
    path("lessons/<int:pk>/", LessonDetailView.as_view(), name="lesson_detail"),
    path("lessons/<int:pk>/vocabulary/", LessonVocabularyView.as_view(), name="lesson_words"),
    path("lessons/<int:pk>/test/", LessonTestView.as_view(), name="lesson_test"),
    path("lessons/<int:pk>/test/submit/", LessonTestSubmitView.as_view(), name="submit_test"),
    path("lessons/<int:pk>/progress/", LessonProgressUpdateView.as_view(), name="save_progress"),
    path("vocabulary/", VocabularyListView.as_view(), name="vocabulary"),
    path("vocabulary/quiz/", VocabularyQuizGenerateView.as_view(), name="vocabulary_quiz"),
    path("vocabulary/quiz/submit/", VocabularyQuizSubmitView.as_view(), name="vocabulary_quiz_submit"),
    path("vocabulary/quiz/history/", VocabularyQuizHistoryView.as_view(), name="vocabulary_quiz_history"),
    path("studio/lessons/template/", StudioLessonTemplateView.as_view(), name="studio_lesson"),
    path("studio/lessons/<int:pk>/", StudioLessonDetailView.as_view(), name="studio_lesson_detail"),
    path("studio/lessons/<int:pk>/tests/", StudioLessonTestsView.as_view(), name="studio_lesson_tests"),
    path("studio/lessons/<int:pk>/vocabulary/", StudioLessonVocabularyView.as_view(), name="studio_lesson_vocabulary"),
    path("studio/vocabulary/", StudioVocabularyView.as_view(), name="studio_vocabulary"),
    path("studio/vocabulary/<int:pk>/", StudioVocabularyDetailView.as_view(), name="studio_vocabulary_detail"),
    path("studio/students/", StudioStudentsProgressView.as_view(), name="studio_students"),
    path("studio/analytics/tests/", StudioTestAnalyticsView.as_view(), name="studio_test_analytics"),
    path("studio/audit/", StudioAuditLogView.as_view(), name="studio_audit_log"),
]
